### ISSUE TITLE
Ortam Değişkenlerinin Gizliliği

### ISSUE THREAD

**Issue by yunusemredilber** [eneskocc/yandex_translate_web_client#1]
https://github.com/eneskocc/yandex-translate-api/blob/8c7fa84a57599e0bf8473d375de4c0ab7b4bc3b6/translate.js#L2

API key gibi secret bilgileri halka açık bir şekilde paylaşmamalısın. Api keyini değiştirip, dotenv gibi bir sisteme geçmeni öneririm

**Comment by eneskocc** [comment]
API keyi blockladım
